services:
  - type: web
    name: mestre-das-passagens-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    # Adicione suas variáveis de ambiente no painel do Render:
    # AMADEUS_API_KEY
    # AMADEUS_API_SECRET

